"""

Revision ID: 3326d4bfb7c3
Revises: 
Create Date: 2026-04-13 10:42:54.844301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3326d4bfb7c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_clients',
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('client_secret', sa.String(), nullable=False),
    sa.Column('redirect_uri', sa.String(length=2048), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('allowed_scopes', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('redirect_uri')
    )
    op.create_index(op.f('ix_oauth_clients_client_id'), 'oauth_clients', ['client_id'], unique=True)
    op.create_table('oauth_users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('firstname', sa.String(length=128), nullable=False),
    sa.Column('lastname', sa.String(length=128), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('email IS NOT NULL OR phone IS NOT NULL', name='ck_user_email_or_phone'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('oauth_authorization_codes',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('redirect_uri', sa.String(length=2048), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=False),
    sa.Column('code_challenge', sa.String(length=256), nullable=False),
    sa.Column('code_challenge_method', sa.String(length=10), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['oauth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_authorization_codes_client_id'), 'oauth_authorization_codes', ['client_id'], unique=False)
    op.create_index(op.f('ix_oauth_authorization_codes_code'), 'oauth_authorization_codes', ['code'], unique=True)
    op.create_table('oauth_authorization_requests',
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('redirect_uri', sa.String(length=2048), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=False),
    sa.Column('code_challenge', sa.String(length=256), nullable=False),
    sa.Column('code_challenge_method', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['oauth_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_authorization_requests_client_id'), 'oauth_authorization_requests', ['client_id'], unique=False)
    op.create_table('oauth_otp',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('otp_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['oauth_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipient', 'otp_type', name='uq_otp_recipient_otp_type')
    )
    op.create_index(op.f('ix_oauth_otp_code'), 'oauth_otp', ['code'], unique=False)
    op.create_index(op.f('ix_oauth_otp_expires_at'), 'oauth_otp', ['expires_at'], unique=False)
    op.create_index(op.f('ix_oauth_otp_otp_type'), 'oauth_otp', ['otp_type'], unique=False)
    op.create_index(op.f('ix_oauth_otp_recipient'), 'oauth_otp', ['recipient'], unique=False)
    op.create_table('oauth_user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('device_type', sa.String(length=20), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('browser', sa.String(length=100), nullable=False),
    sa.Column('os', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['oauth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_user_sessions_session_id'), 'oauth_user_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_oauth_user_sessions_user_id'), 'oauth_user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_user_sessions_user_id'), table_name='oauth_user_sessions')
    op.drop_index(op.f('ix_oauth_user_sessions_session_id'), table_name='oauth_user_sessions')
    op.drop_table('oauth_user_sessions')
    op.drop_index(op.f('ix_oauth_otp_recipient'), table_name='oauth_otp')
    op.drop_index(op.f('ix_oauth_otp_otp_type'), table_name='oauth_otp')
    op.drop_index(op.f('ix_oauth_otp_expires_at'), table_name='oauth_otp')
    op.drop_index(op.f('ix_oauth_otp_code'), table_name='oauth_otp')
    op.drop_table('oauth_otp')
    op.drop_index(op.f('ix_oauth_authorization_requests_client_id'), table_name='oauth_authorization_requests')
    op.drop_table('oauth_authorization_requests')
    op.drop_index(op.f('ix_oauth_authorization_codes_code'), table_name='oauth_authorization_codes')
    op.drop_index(op.f('ix_oauth_authorization_codes_client_id'), table_name='oauth_authorization_codes')
    op.drop_table('oauth_authorization_codes')
    op.drop_table('oauth_users')
    op.drop_index(op.f('ix_oauth_clients_client_id'), table_name='oauth_clients')
    op.drop_table('oauth_clients')
    # ### end Alembic commands ###
