name: Build & Push Docker Image

on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: ${{ vars.DOCKER_REGISTRY }}/${{ github.repository }}
  TAG: ${{ github.ref_name }}

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker registry
        run: |
          echo "${{ secrets.DOCKER_REGISTRY_TOKEN }}" | docker login ${{ vars.DOCKER_REGISTRY }} \
            -u "${{ secrets.DOCKER_REGISTRY_USER }}" \
            --password-stdin

      - name: Build image
        run: |
          make docker-build \
            PROJECT_NAME=${{ env.IMAGE_NAME }} \
            IMAGE_TAG=${{ env.TAG }} \
            IMAGE_SHA=${{ github.sha }}

      - name: Push images
        run: |
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:sha-${{ github.sha }}
          docker push $IMAGE_NAME:latest
