name: Test

on:
  push:
    branches:
      - "*"

env:
  CONTAINER_NAME: ${{ github.event.repository.name }}
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
            pip install poetry
            poetry config virtualenvs.in-project true
            poetry install --no-root
            export PATH=".venv/bin:$PATH"
            make test-all
